apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_URL: {{ .Values.app.db.url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-config-secret
type: Opaque
data:
  DB_USER: {{ .Values.app.db.username | b64enc }}
  DB_PASS: {{ .Values.app.db.password | b64enc }}